import axios from "axios";

import { ensureApiKey, resolveAgentName } from "./auth";
import { debugDump, isDebugMode } from "./debug";
import pkg from "../package.json";

const LINEAR_API_URL = "https://api.linear.app/graphql";

/**
 * Returns the GraphQL endpoint to use. When LINEAR_PROXY_URL is set, all
 * requests route through the connector proxy (Phase 0B, design.md §4.6)
 * instead of hitting api.linear.app directly. The proxy is transparent in
 * v0; future phases add per-step instruction injection and command validation.
 */
function resolveApiUrl(): string {
  return process.env.LINEAR_PROXY_URL ?? LINEAR_API_URL;
}

/**
 * Current semantic intent, set by the active semantic command before it issues
 * any GraphQL calls. The proxy reads this to enforce per-command rules
 * (Phase 2, design.md §11). Cleared by the command after completion.
 */
let _proxyIntent: string | undefined;

/**
 * Set the active semantic intent for the duration of a command.
 * Pass `undefined` to clear. Only affects proxied requests;
 * no-op when LINEAR_PROXY_URL is unset.
 */
export function setProxyIntent(intent: string | undefined): void {
  _proxyIntent = intent;
}

/**
 * AI-2530: per-invocation command identity. A random UUID minted once per
 * `linear <command>` invocation and attached to every GraphQL request via
 * the `X-Openclaw-Command-Id` header. The connector keys its auth-snapshot
 * on `agentId:issueId:intent:commandId` so that a fresh command always
 * re-derives from live state, while chunked follow-ups from the same
 * command (AI-2472) share the nonce and reuse the snapshot.
 *
 * Generated by `setProxyCommandId()` in `runCommand()`; cleared by the
 * same function after the command completes. Never set this directly from
 * a semantic command handler.
 */
let _proxyCommandId: string | undefined;

/**
 * Set the per-invocation command nonce for the duration of a command.
 * Pass `undefined` to clear. Called by `runCommand()` in index.ts, not by
 * individual command handlers.
 */
export function setProxyCommandId(id: string | undefined): void {
  _proxyCommandId = id;
}

let _proxyTarget: string | undefined;

export function setProxyTarget(target: string | undefined): void {
  _proxyTarget = target;
}

let _proxyBreakGlass: boolean | undefined;

/**
 * AI-482: Set whether to include the X-Openclaw-Break-Glass header.
 * Allows stewards to bypass enforcement for emergency recovery.
 */
export function setProxyBreakGlass(enabled: boolean | undefined): void {
  _proxyBreakGlass = enabled;
}

/**
 * AI-1769 AC2: when a governed transition's required comment was suppressed as a
 * near-duplicate of an existing comment, the CLI still sends the transition
 * mutation and points the proxy at the comment that already carries the
 * feedback. The proxy verifies the referenced comment before treating a
 * requires_comment gate as satisfied.
 */
let _proxyCommentSatisfiedBy: string | undefined;

export function setProxyCommentSatisfiedBy(commentId: string | undefined): void {
  _proxyCommentSatisfiedBy = commentId;
}

/**
 * AI-2479: the code artifact (`<branch>@<sha>`) a handoff declares, and an
 * optional reason for declaring one that differs from the artifact the caller
 * was handed. The proxy compares the declaration against the ticket's recorded
 * disclosure and refuses an undeclared substitution.
 *
 * These are advisory in the CLI and enforced in the connector, deliberately: the
 * CLI is the component being bypassed, so only the proxy — which resolves the
 * caller from an unforgeable OAuth token — can enforce anything here.
 */
let _proxyCodeArtifact: string | undefined;
let _proxySubstitutionReason: string | undefined;

export function setProxyCodeArtifact(artifact: string | undefined): void {
  _proxyCodeArtifact = artifact;
}

export function setProxySubstitutionReason(reason: string | undefined): void {
  _proxySubstitutionReason = reason;
}

/**
 * Extra headers to attach when routing through the proxy so it can identify
 * the calling agent for logging and enforcement (Phase 2, design.md §11).
 *
 * Uses resolveAgentName() from auth.ts so the proxy header and the secret
 * file lookup can never drift — both derive identity from the same sources.
 */
function proxyHeaders(): Record<string, string> {
  const proxyUrl = process.env.LINEAR_PROXY_URL;
  if (!proxyUrl) return {};
  const agentId = resolveAgentName().name ?? "unknown";
  const headers: Record<string, string> = {
    "X-Openclaw-Agent": agentId,
    "X-Openclaw-Linear-Cli-Version": pkg.version,
  };
  if (_proxyIntent) headers["X-Openclaw-Linear-Intent"] = _proxyIntent;
  if (_proxyCommandId) headers["X-Openclaw-Command-Id"] = _proxyCommandId;
  if (_proxyTarget) headers["X-Openclaw-Linear-Target"] = _proxyTarget;
  if (_proxyBreakGlass) headers["X-Openclaw-Break-Glass"] = "true";
  if (_proxyCommentSatisfiedBy) headers["X-Openclaw-Comment-Satisfied-By"] = _proxyCommentSatisfiedBy;
  if (_proxyCodeArtifact) headers["X-Openclaw-Code-Artifact"] = _proxyCodeArtifact;
  // Percent-encoded: the reason is agent-authored free text and routinely
  // contains non-latin-1 characters (em-dashes, emoji). Node throws on a header
  // value it cannot encode, which would turn a declared substitution — the
  // sanctioned path — into a hard crash. The connector decodes it back.
  if (_proxySubstitutionReason) {
    headers["X-Openclaw-Substitution-Reason"] = encodeURIComponent(_proxySubstitutionReason);
  }
  return headers;
}

export interface GraphQLErrorDetail {
  message: string;
  path?: (string | number)[];
  extensions?: Record<string, unknown>;
}

interface LinearGraphQLResponse<T> {
  data?: T;
  errors?: GraphQLErrorDetail[];
}

interface HintRule {
  test: (msg: string) => boolean;
  hint: string;
}

const HINT_RULES: HintRule[] = [
  {
    test: (msg) => /self.?reference|cannot reference/i.test(msg),
    hint: "Comment body contains a bare issue identifier that references the issue itself. Replace hyphens with em-dashes (—) or spell out the ID.",
  },
  {
    test: (msg) => /too long|exceeds.*length|max.*length/i.test(msg),
    hint: "Comment body exceeds the maximum length. Split into multiple comments or shorten.",
  },
  {
    test: (msg) => /team/.test(msg) && /label/i.test(msg),
    hint: "Label belongs to a different team than the issue. Use a label from the same team, or check the team prefix.",
  },
];

function resolveHint(message: string): string | undefined {
  for (const rule of HINT_RULES) {
    if (rule.test(message)) return rule.hint;
  }
  if (/Argument Validation Error/i.test(message)) {
    return "A field failed validation. Re-run with --debug to see the raw GraphQL error details.";
  }
  return undefined;
}

function enrichMessage(errors: GraphQLErrorDetail[]): string {
  const parts: string[] = [];

  for (const err of errors) {
    const fieldPath = err.path?.join(".");
    const hint = resolveHint(err.message);
    const userMsg = err.extensions?.userPresentableMessage;

    parts.push(err.message);

    if (fieldPath) {
      parts.push(`  ↳ field: ${fieldPath}`);
    }

    // Surface the API's own validation details when available
    if (userMsg && typeof userMsg === "string" && userMsg !== err.message) {
      parts.push(`  ↳ detail: ${userMsg}`);
    }

    if (hint) {
      parts.push(`  ↳ hint: ${hint}`);
    }
  }

  return parts.join("\n");
}

/** Retry backoff intervals for ECONNREFUSED (ms). ~4.5s total window. */
const ECONNREFUSED_RETRY_DELAYS = [500, 1000, 2000];

/**
 * True when the error is a network-level connection refusal — the target host
 * is reachable but nothing is listening on the port (ECONNREFUSED). This is
 * the signature of a deploy-restart gap on the connector proxy.
 */
function isConnectionRefused(error: unknown): boolean {
  if (!axios.isAxiosError(error)) return false;
  // axios wraps ECONNREFUSED as a network error with no .response and no .status
  if (error.response) return false;
  const msg = (error.message ?? "").toLowerCase();
  return msg.includes("econnrefused") || msg.includes("connect ec") || msg.includes("connection refused");
}

/**
 * Sleep helper for retry backoff.
 */
function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

export class LinearApiError extends Error {
  code?: string;
  details?: GraphQLErrorDetail[];

  constructor(message: string, code?: string, details?: GraphQLErrorDetail[]) {
    super(message);
    this.name = "LinearApiError";
    this.code = code;
    this.details = details;
  }
}

/**
 * Execute one GraphQL request, returning the axios response or throwing.
 */
async function executeGraphQL<T>(
  apiUrl: string,
  query: string,
  variables: Record<string, unknown> | undefined,
  headers: Record<string, string>
) {
  return await axios.post<LinearGraphQLResponse<T>>(
    apiUrl,
    { query, variables },
    { headers }
  );
}

export async function linearGraphQL<T>(
  query: string,
  variables?: Record<string, unknown>
): Promise<T> {
  const apiKey = ensureApiKey();
  const apiUrl = resolveApiUrl();
  // Build headers once; they don't change across retries.
  const headers: Record<string, string> = {
    Authorization: apiKey,
    "Content-Type": "application/json",
    ...proxyHeaders(),
  };
  const maxAttempts = ECONNREFUSED_RETRY_DELAYS.length + 1;
  let lastError: unknown;

  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      const response = await executeGraphQL<T>(apiUrl, query, variables, headers);

      if (response.data.errors?.length) {
        debugDump("GraphQL errors", response.data.errors);
        throw new LinearApiError(
          enrichMessage(response.data.errors),
          "GRAPHQL_ERROR",
          response.data.errors
        );
      }

      if (!response.data.data) {
        throw new LinearApiError("Linear API returned no data.", "NO_DATA");
      }

      return response.data.data;
    } catch (error) {
      if (axios.isAxiosError(error)) {
        if (error.response) {
          // Server responded with an HTTP error — not a connection-refused flap.
          // Throw immediately; retrying won't help.
          const errors = (error.response.data?.errors ?? []) as GraphQLErrorDetail[];
          if (error.response.status === 401) {
            throw new LinearApiError("Unauthorized", "UNAUTHORIZED");
          }
          debugDump("HTTP error response", error.response.data);
          const message = errors.length
            ? enrichMessage(errors)
            : `Linear API returned HTTP ${error.response.status}: ${error.response.statusText}`;
          throw new LinearApiError(message, `HTTP_${error.response.status}`, errors);
        }

        // Network error with no response — could be ECONNREFUSED (deploy flap)
        // or a genuine connectivity issue. Retry on connection-refused signals.
        if (isConnectionRefused(error) && attempt < maxAttempts) {
          const delay = ECONNREFUSED_RETRY_DELAYS[attempt - 1];
          if (isDebugMode()) {
            console.error(`[debug] ECONNREFUSED on attempt ${attempt}/${maxAttempts} — retrying in ${delay}ms`);
          }
          await sleep(delay);
          lastError = error;
          continue;
        }

        throw new LinearApiError(
          `Network request to Linear API failed: ${error.message}. Check your internet connection and that api.linear.app is reachable.`,
          "NETWORK_ERROR"
        );
      }
      throw error;
    }
  }

  // Exhausted retries — surface the last connection-refused error with a clear message.
  const msg = lastError instanceof Error
    ? lastError.message
    : String(lastError);
  throw new LinearApiError(
    `GraphQL request failed after ${maxAttempts} attempts: ${msg}. The connector proxy at ${apiUrl} may still be restarting or unreachable.`,
    "NETWORK_ERROR"
  );
}

export async function putPresignedFile(
  url: string,
  content: Buffer,
  contentType: string,
  extraHeaders?: Array<{ key: string; value: string }>
): Promise<void> {
  const headers: Record<string, string> = {
    "Content-Type": contentType,
    "Content-Length": String(content.byteLength),
  };

  for (const header of extraHeaders ?? []) {
    headers[header.key] = header.value;
  }

  await axios.put(url, content, {
    headers,
  });
}
